import { SlashCommandBuilder, EmbedBuilder, MessageFlags } from "discord.js";
import { v4 as uuidv4 } from "uuid";
import { Database } from "../db/index.js";

export const data = new SlashCommandBuilder()
	.setName("generate-apikey")
	.setDescription("Generates an API key for the bot (Admin only)");

export async function execute(interaction, BMConfig = {}) {
	const member = interaction.member;

	if (!member.roles.cache.has(BMConfig.adminRole)) {
		return await interaction.reply({
			content: "You need the Admin role to use this command!",
			ephemeral: true,
		});
	}

	const apiKey = uuidv4();
	Database.update(({ keys }) =>
		keys.push({ member: interaction.user.tag, key: apiKey }),
	);

	const apiKeyEmbed = new EmbedBuilder()
		.setColor("#00ff00")
		.setTitle("API Key Generated")
		.setDescription("A new API key has been generated for BadManiac.")
		.addFields(
			{ name: "API Key", value: "```" + apiKey + "```" },
			{
				name: "Note",
				value: "This key has been logged to the console. Store it securely!",
			},
		)
		.setTimestamp()
		.setFooter({
			text: `Generated by ${interaction.user.username}`,
			iconURL: interaction.user.displayAvatarURL({ dynamic: true }),
		});

	await interaction.reply({
		embeds: [apiKeyEmbed],
		flags: MessageFlags.Ephemeral,
	});
}
